APP_NAME: "category-service"
APP_HTTP_PORT: "9002"
DB_NAME: "categorydb"
DB_PORT: "5432"
DB_HOST: "categorydb"
DB_PASSWORD: "pass"
DB_USER: "user"
TIMEZONE: "Asia/Jakarta"
Access_Token: 'secret123'
Refresh_Token: 'secret321'
