APP_NAME: "user-service"
APP_HTTP_PORT: "50051"
DB_NAME: "userdb"
DB_PORT: "5432"
DB_HOST: "userdb"
DB_PASSWORD: "pass"
DB_USER: "user"
TIMEZONE: "Asia/Jakarta"
Access_Token: 'secret123'
Refresh_Token: 'secret321'
