APP_NAME: "author-service"
APP_HTTP_PORT: "9003"
DB_NAME: "authordb"
DB_PORT: "5432"
DB_HOST: "authordb"
DB_PASSWORD: "pass"
DB_USER: "user"
TIMEZONE: "Asia/Jakarta"
Access_Token: 'secret123'
Refresh_Token: 'secret321'
